spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco?autoReconnect=true&useSSL=false
    username: userroot
    password: userroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    max-wait: 10000
    max-active: 50
    test-on-borrow: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        hbm2ddl.import_files: inserts_basic.sql
      dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8090