spring:
  datasource:
    url: jdbc:mysql://localhost/banco
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    max-wait: 10000
    max-active: 50
    test-on-borrow: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        hbm2ddl.import_files: inserts_basic.sql
server:
  port: 8090